#nohup python getGitLog.py projects/top_C++/ > cpp.out 2>cpp.err &
#./run.sh projects/top_C++/TideSDK
#./run.sh projects/top_C++/bitcoin
#./run.sh projects/top_C++/brackets-app
#./run.sh projects/top_C++/capnproto
./run.sh projects/top_C++/DOOM-3-BFG
./run.sh projects/top_C++/doom3.gpl
./run.sh projects/top_C++/fish-shell
./run.sh projects/top_C++/folly
./run.sh projects/top_C++/fr_public
./run.sh projects/top_C++/grive
./run.sh projects/top_C++/hiphop-php
./run.sh projects/top_C++/mongo
./run.sh projects/top_C++/mosh
./run.sh projects/top_C++/node-webkit
./run.sh projects/top_C++/opencv
./run.sh projects/top_C++/OpenSubdiv
./run.sh projects/top_C++/pdf2htmlEX
./run.sh projects/top_C++/phantomjs
./run.sh projects/top_C++/rethinkdb
./run.sh projects/top_C++/rocksdb
./run.sh projects/top_C++/source-sdk-2013
./run.sh projects/top_C++/subvim
./run.sh projects/top_C++/tiled
./run.sh projects/top_C++/Torque3D
./run.sh projects/top_C++/TrinityCore
./run.sh projects/top_C++/vowpal_wabbit
